#perl

=pod

Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:
1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.

=cut

use warnings;
use strict;

my @nums = (1,2);
while ($nums[-1]<4*10**6){
    $nums[$#nums+1]=$nums[-1]+$nums[-2]
}
pop @nums;
my $sum = 0;
foreach (@nums){$sum+=$_ unless $_%2!=0;}
print "\n\tAnswer: $sum.";

