#perl

=pod

project euler problem 12

The sequence of triangle numbers is generated by adding the natural numbers.
So the 7th triangle number would be 1 + 2 + 3 + 4 + 5 + 6 + 7 = 28. The first ten terms would be:

1, 3, 6, 10, 15, 21, 28, 36, 45, 55, ...

Let us list the factors of the first seven triangle numbers:

 1: 1
 3: 1,3
 6: 1,2,3,6
10: 1,2,5,10
15: 1,3,5,15
21: 1,3,7,21
28: 1,2,4,7,14,28
We can see that 28 is the first triangle number to have over five divisors.

What is the value of the first triangle number to have over five hundred divisors?
=cut

use warnings;
use strict;

use Time::HiRes;
my $time = [Time::HiRes::gettimeofday()];

my $tri = 1;
sub divs{my $divs = 0;foreach (1..int(sqrt($_[0]))){if ($_[0]%$_==0){$divs+=2;}}return $divs;}
LOOP: for (my $i=2;;$i++){last LOOP if divs($tri)>500;$tri+=$i;}

$time=Time::HiRes::tv_interval($time);
print "\n\tAnswer: $tri. ($time seconds)\n";

